name: Gitleaks Secret Detection

"on":
  pull_request:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

jobs:
  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc  # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload Gitleaks report as artifact
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: gitleaks-report
          path: |
            **/gitleaks-report.json
            **/gitleaks-report.sarif
          retention-days: 30
